import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from typing import Dict, Any

class PdfExporter:
    @staticmethod
    def generate(report_id: str, report_data: Dict[str, Any], output_path: str) -> str:
        file_path = os.path.join(output_path, f"{report_id}.pdf")
        
        doc = SimpleDocTemplate(file_path, pagesize=letter)
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle', parent=styles['Heading1'], fontSize=18, spaceAfter=20, alignment=1 # Center
        )
        h2_style = ParagraphStyle(
            'CustomH2', parent=styles['Heading2'], fontSize=14, spaceBefore=15, spaceAfter=10
        )
        body_style = styles["Normal"]
        
        elements = []
        
        # Header
        elements.append(Paragraph("HOSPITAL MANAGEMENT SYSTEM", title_style))
        elements.append(Paragraph("AI REPORT BUILDER", title_style))
        elements.append(Spacer(1, 20))
        
        # Metadata
        elements.append(Paragraph(f"<b>Report Type:</b> {report_data['report_type'].upper()}", body_style))
        elements.append(Paragraph(f"<b>Date Range:</b> {report_data.get('date_range', 'N/A')}", body_style))
        elements.append(Paragraph(f"<b>Generated On:</b> {report_data.get('generated_date', 'N/A')}", body_style))
        elements.append(Spacer(1, 20))
        
        # Executive Summary
        elements.append(Paragraph("EXECUTIVE SUMMARY", h2_style))
        elements.append(Paragraph(report_data.get('summary', 'No summary available.'), body_style))
        elements.append(Spacer(1, 15))
        
        # KPI Summary
        elements.append(Paragraph("KPI SUMMARY", h2_style))
        kpi_data = [["Metric", "Value"]]
        for k, v in report_data.get('kpis', {}).items():
            kpi_data.append([k.replace('_', ' ').title(), str(v)])
            
        if len(kpi_data) > 1:
            t = Table(kpi_data, colWidths=[200, 200])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f3f4f6')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#e5e7eb'))
            ]))
            elements.append(t)
        
        elements.append(Spacer(1, 20))
        
        # Detailed Analysis
        elements.append(Paragraph("DETAILED ANALYSIS", h2_style))
        elements.append(Paragraph("Refer to the charts in the digital dashboard for visual trend lines and distributions. The data subset is provided below.", body_style))
        elements.append(Spacer(1, 15))
        
        # Footer
        elements.append(Spacer(1, 30))
        elements.append(Paragraph("--------------------------------", body_style))
        elements.append(Paragraph("Generated by HMS AI Report Builder", body_style))
        
        doc.build(elements)
        return file_path
