"""Init procurement models

Revision ID: 945e101b5de9
Revises: 
Create Date: 2026-08-23 22:16:00.872670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '945e101b5de9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False)
    op.add_column('inventory_items', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('batch_number', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('unit', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('inventory_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_inventory_items_category'), 'inventory_items', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_items_sku'), 'inventory_items', ['sku'], unique=True)
    op.drop_column('inventory_items', 'daily_consumption')
    op.add_column('purchase_orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('purchase_orders', sa.Column('expected_delivery_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('purchase_orders', 'order_date')
    op.add_column('vendors', sa.Column('contact_person', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('email', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('address', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('average_delivery_days', sa.Integer(), nullable=True))
    op.add_column('vendors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('vendors', 'contact_email')
    op.drop_column('vendors', 'delivery_time_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('delivery_time_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vendors', 'created_at')
    op.drop_column('vendors', 'average_delivery_days')
    op.drop_column('vendors', 'address')
    op.drop_column('vendors', 'phone')
    op.drop_column('vendors', 'email')
    op.drop_column('vendors', 'contact_person')
    op.add_column('purchase_orders', sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('purchase_orders', 'expected_delivery_date')
    op.drop_column('purchase_orders', 'created_at')
    op.add_column('inventory_items', sa.Column('daily_consumption', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_inventory_items_sku'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_category'), table_name='inventory_items')
    op.drop_column('inventory_items', 'updated_at')
    op.drop_column('inventory_items', 'created_at')
    op.drop_column('inventory_items', 'unit')
    op.drop_column('inventory_items', 'batch_number')
    op.drop_column('inventory_items', 'sku')
    op.drop_index(op.f('ix_purchase_order_items_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    # ### end Alembic commands ###
