"""Add satisfaction_score to Patient

Revision ID: bbac30f6a1a4
Revises: 13b4c1226124
Create Date: 2026-08-17 09:52:53.706826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbac30f6a1a4'
down_revision: Union[str, Sequence[str], None] = '13b4c1226124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('satisfaction_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'satisfaction_score')
    # ### end Alembic commands ###
